# local port to use
NEXUS_PORT: 5000
# Needs to be Java 8 to support all gradle wrapper versions
# JAVA_HOME: "C:/Program Files/Java/openlogic-openjdk-8u422-b05-windows-x64/"
JAVA_HOME:
    "1.8": "C:/Program Files/Java/openlogic-openjdk-8u422-b05-windows-x64/"
    "1.11": "C:/Program Files/Java/jdk-11.0.2/"

# Make sure to accept the license for the sdk.
ANDROID_SDK_ROOT: "C:/Users/kaiha/AppData/Local/Android/Sdk"

# repos
KNOWN_HOSTS:
    "com.github": "github.com"
    "com.azure": "azure.com"
    "com.gitee": "gitee.com"
    "org.bitbucket": "bitbucket.com"
    "com.gitlab": "gitlab.com"
    "com.mycustom-example-host": "mycustom-example-host.com/repos"
REPOSITORY_TOKENS:
    ExampleNameProvider: "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"

# Cleanup
DELETE_ARTIFACTS: -1
DELETE_TMP: -1