# Example file needs to be customized for local environment:
# and then renamed to ./config.yml

# local port to use
NEXUS_PORT: 5000
# JAVA_HOME: "C:/Program Files/Java/openlogic-openjdk-8u422-b05-windows-x64/"
JAVA_HOME:
    "1.8": "C:/Program Files/Java/openlogic-openjdk-8u422-b05-windows-x64/"

# Make sure to accept the license for the sdk.
ANDROID_SDK_ROOT: "C:/Users/user/AppData/Local/Android/Sdk"

# repos
KNOWN_HOSTS:
    # package prefix : url prefix
    "com.github": "github.com"
    "com.azure": "azure.com"
    "com.gitee": "gitee.com"
    "org.bitbucket": "bitbucket.com"
    "com.gitlab": "gitlab.com"
    "com.mycustom-example-host": "mycustom-example-host.com/repos"
REPOSITORY_TOKENS:
    ExampleNameProvider: "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"

# Cleanup schedule in days.
DELETE_ARTIFACTS: -1
DELETE_TMP: -1