# local port to use
NEXUS_PORT: 5000
# Needs to be Java 8 to support all gradle wrapper versions
JAVA_HOME: "C:/Program Files/Java/openlogic-openjdk-8u422-b05-windows-x64/"
# Make sure to accept the license for the sdk.
ANDROID_SDK_ROOT: "C:/Users/kaiha/AppData/Local/Android/Sdk"

# repos
KNOWN_HOSTS:
    "com.github": "github.com/repos"
REPOSITORY_TOKENS:
    ExampleNameProvider: "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"

# Cleanup
DELETE_ARTIFACTS: -1
DELETE_TMP: -1