FROM python:3.11-alpine

ENV ANDROID_HOME=/opt/android-sdk
ENV PATH="${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools"

RUN apk update && apk add --no-cache \
    openjdk8-jdk \
    openjdk11-jdk \
    openjdk17-jdk \
    bash \
    curl \
    wget \
    unzip \
    git \
    build-base \
    python3-dev \
    py3-pip \
    py3-venv

RUN mkdir -p ${ANDROID_HOME} && \
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip && \
    unzip commandlinetools.zip -d ${ANDROID_HOME} && \
    rm commandlinetools.zip && \
    yes | sdkmanager --licenses && \
    sdkmanager "platform-tools" "platforms;android-30"

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
VOLUME ["/app/repo"]

EXPOSE 5000
CMD ["python3", "src/__init__.py"]