# Docker Config File.
NEXUS_PORT: 5000

JAVA_HOME:
    "1.8": "C:/Program Files/Java/openlogic-openjdk-8u422-b05-windows-x64/"
    "1.11": "C:/Program Files/Java/jdk-11.0.2/"
    "1.12": "C:/Program Files/Java/jdk-12.0.2/"
    "1.17": "C:/Program Files/Java/jdk-17/"
    "1.21": "C:/Program Files/Java/jdk-21/"

# Make sure to accept the license for the sdk.
ANDROID_SDK_ROOT: "C:/Users/kaiha/AppData/Local/Android/Sdk"

# repos
KNOWN_HOSTS:
    # package prefix : url prefix
    "com.github": "github.com"
    "com.azure": "azure.com"
    "com.gitee": "gitee.com"
    "org.bitbucket": "bitbucket.com"
    "com.gitlab": "gitlab.com"

# Cleanup schedule in days.
DELETE_ARTIFACTS: -1
DELETE_TMP: -1